### ISSUE TITLE
Update to Current Release?

### ISSUE THREAD

**Issue by JERW86** [Magisk-Modules-Repo/dnscrypt-proxy-magisk#15]
@bluemeda - would you please consider updating to the current release (2.0.14 as of this writing)? [Changelog](https://github.com/jedisct1/dnscrypt-proxy/blob/master/ChangeLog) and [Code Changes](https://github.com/jedisct1/dnscrypt-proxy/commits/master). Thank you for your time and effort.

**Comment by bluemeda** [comment]
@JERW86 wait for a moment, I have a little free time in Ramadhan.

**Comment by bluemeda** [comment]
@JERW86 done
