### ISSUE TITLE
The latest version stoped to work with "DNS Manager Pro"

### ISSUE THREAD

**Issue by sam-kzn** [Magisk-Modules-Repo/dnscrypt-proxy-magisk#2]
Hi!
I'm using the Magisk module "DNSCrypt-Proxy" and "DNS Manager Pro" (https://dnsmanager.me/) for a long time.
But since update to the latest version of "DNSCrypt-Proxy" (2.1.1) the network stopped to work (ERR_NAME_NOT_RESOLVED).
The network up to work only after disabling or uninstalling the "DNS Manager Pro".
Does the problem arise from "DNSCrypt-Proxy" bug or from the "DNS Manager Pro" which doesn't support new protocol?
Thank You!

**Comment by bluemeda** [comment]
@sam-kzn dns-changer app is not needed in this module because its automatically forward dns request to dnscrypt.

**Comment by sam-kzn** [comment]
Thank You for answer!
