### ISSUE TITLE
v4a

### ISSUE THREAD

**Issue by JohnFawkes** [Magisk-Modules-Repo/dnscrypt-proxy-magisk#6]
something in your services script is causing the ViPER4Android icon to dissappear. deleting your service. sh and rebooting makes v4a come back

**Comment by Zackptg5** [comment]
Fix in pull request #7

**Comment by JohnFawkes** [comment]
this module is not the cause  of v4a disappearing. its another module. i still would recommend changing the service script to what zackptg5 suggested

**Comment by bluemeda** [comment]
pul request already merged
