### ISSUE TITLE
[bug][service.sh] iptables rules still referencing :5354

### ISSUE THREAD

**Issue by rprimus** [Magisk-Modules-Repo/dnscrypt-proxy-magisk#9]
Sun Apr  1 14:44:21 BST 2018

HI,

Just upgraded to latest version (having modified `dnsscrypt-proxy.toml` to use port 53 (see https://github.com/jedisct1/dnscrypt-proxy/issues/226).

`service.sh` iptables rules still forward to `:5353`.   This port should be removed.

**Comment by rprimus** [comment]
Mon Apr  2 09:28:50 BST 2018

My bad - didn't realise port was changed to `:5354`.

**Comment by rprimus** [comment]
Wed Apr 18 11:48:31 BST 2018

For v2.3.0,  `port 5354` has been replaced with the standard `port 53`.  The installation instructions also make reference to `port 53` in the `Auto redirect` instructions.

`service.sh` still sets up iptables rules to `port 5354`

**Comment by bluemeda** [comment]
@rprimus if you choose auto redirect through iptables, it use 5354. but if you choose manually set dns, it use standard port 53.

**Comment by rprimus** [comment]
On Sat, Apr 21, 2018 at 12:57:09AM -0700, Affif Mukhlashin wrote:
>@rprimus if you choose auto redirect through iptables, it use 5354. but if you choose manually set dns, it use standard port 53.

Sat 21 Apr 2018 10:31:28 BST

@bluemeda - thank you for the clarification.  What's the reason for using 
the non-standard port (535x) and not 53 always?

-- 
-primus (Train yourself and be your own master.)
"First, solve the problem.  Then, write the code." - John Johnson
"Narrowness of experience leads to narrowness of imagination." - Rob Pike
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by bluemeda** [comment]
@rprimus port 53 is used by default android while tethering. port 5353 is used by chrome cast (jedisct1/dnscrypt-proxy#226)
so, why I still use 53 for manual mode? because some of dns changer apps only support 53 as dns port.

**Comment by rprimus** [comment]
On Mon, Apr 23, 2018 at 02:03:47AM -0700, Affif Mukhlashin wrote:
>@rprimus port 53 is used by default android while tethering. port 5353 is used by chrome cast (jedisct1/dnscrypt-proxy#226)
>so, why I still use 53 for manual mode? because some of dns changer apps only support 53 as dns port.

Mon 23 Apr 2018 10:09:47 BST

@bluemeda - I was asking why use port 5354?

-- 
-primus (Train yourself and be your own master.)
"First, solve the problem.  Then, write the code." - John Johnson
"Narrowness of experience leads to narrowness of imagination." - Rob Pike
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
